## autostart
exec-once=~/.config/mango/autostart.sh

## source modules
source=./modules/host.conf
source=./modules/laptop.conf
source=./modules/layouts.conf
source=./modules/rules.conf
source=./modules/misc.conf
source=./modules/inputs.conf
source=./modules/style.conf
source=./modules/colors.conf
source=./modules/binds.conf
