## screenshots
bind=NONE,Print,spawn,screenshot fullscreen
bind=SHIFT,Print,spawn,screenshot region
bind=CTRL+SHIFT,Print,spawn,screenshot window
bind=SUPER,Print,spawn,screenshot annotate

## volume control
binds=none,XF86AudioRaiseVolume,spawn,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ -l 1.0
binds=none,XF86AudioLowerVolume,spawn,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
binds=none,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

## launcher
bindr=Super,Super_L,toggle_named_scratchpad,launcher,none,footclient --app-id=launcher otter-launcher

## app shortcuts
bind=SUPER,Return,spawn,footclient
binds=SUPER,v,spawn,footclient nvim
binds=SUPER,b,spawn,helium-browser

## closing apps
binds=SUPER,q,killclient
binds=SHIFT+SUPER,q,killclient,force

## focus window
bind=SUPER,Tab,focusstack,next
binds=SUPER,h,focusdir,left
binds=SUPER,l,focusdir,right
binds=SUPER,k,focusdir,up
binds=SUPER,j,focusdir,down

## move window
binds=SHIFT+SUPER,k,exchange_client,up
binds=SHIFT+SUPER,j,exchange_client,down
binds=SHIFT+SUPER,h,exchange_client,left
binds=SHIFT+SUPER,l,exchange_client,right

## window state
bind=SUPER,space,togglefloating
bind=SUPER,g,toggleglobal,
bind=SHIFT+SUPER,g,togglemaximizescreen,

## overview
bind=ALT,Tab,togglejump,
binds=SUPER,f,togglefullscreen,
binds=SHIFT+SUPER,f,togglefakefullscreen,
binds=SUPER,i,minimized,
binds=SUPER,o,toggleoverlay,
binds=SUPER+SHIFT,I,restore_minimized
binds=ALT,z,toggle_scratchpad

## scroller layout
bind=ALT,e,set_proportion,1.0
bind=ALT,x,switch_proportion_preset,

## switch tag
binds=SUPER,1,view,1,0
binds=SUPER,2,view,2,0
binds=SUPER,3,view,3,0
binds=SUPER,4,view,4,0
binds=SUPER,5,view,5,0
binds=SUPER,6,view,6,0
binds=SUPER,7,view,7,0
binds=SUPER,8,view,8,0
binds=SUPER,9,view,9,0

## move client to tag and focus
bind=SUPER+SHIFT,1,tag,1,0
bind=SUPER+SHIFT,2,tag,2,0
bind=SUPER+SHIFT,3,tag,3,0
bind=SUPER+SHIFT,4,tag,4,0
bind=SUPER+SHIFT,5,tag,5,0
bind=SUPER+SHIFT,6,tag,6,0
bind=SUPER+SHIFT,7,tag,7,0
bind=SUPER+SHIFT,8,tag,8,0
bind=SUPER+SHIFT,9,tag,9,0

## resize mouse
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_middle,togglemaximizescreen,0
mousebind=SUPER,btn_right,moveresize,curresize

## resize
binds=SUPER+CTRL,k,resizewin,+0,-50
binds=SUPER+CTRL,j,resizewin,+0,+50
binds=SUPER+CTRL,h,resizewin,-50,+0
binds=SUPER+CTRL,l,resizewin,+50,+0

## group
binds=SUPER+CTRL,g,groupjoin,left

## layouts
binds=SUPER,m,setkeymode,mode_layout

## monocle
keymode=mode_layout
bindsc=NONE,m,setlayout,monocle
bindsc=NONE,m,setkeymode,default

## dwindle
bindsc=NONE,w,setlayout,dwindle
bindsc=NONE,w,setkeymode,default

## tile
bindsc=NONE,t,setlayout,tile
bindsc=NONE,t,setkeymode,default
bindsc=SHIFT,t,setlayout,vertical_tile
bindsc=SHIFT,t,setkeymode,default
bindsc=CTRL,t,setlayout,right_tile
bindsc=CTRL,t,setkeymode,default
bindsc=CTRL+SHIFT,t,setlayout,center_tile
bindsc=CTRL+SHIFT,t,setkeymode,default

## scroller
bindsc=NONE,s,setlayout,scroller
bindsc=NONE,s,setkeymode,default
bindsc=SHIFT,s,setlayout,vertical_scroller
bindsc=SHIFT,s,setkeymode,default

## grid
bindsc=NONE,g,setlayout,grid
bindsc=NONE,g,setkeymode,default
bindsc=SHIFT,g,setlayout,vertical_grid
bindsc=SHIFT,g,setkeymode,default

## deck
bindsc=NONE,d,setlayout,deck
bindsc=NONE,d,setkeymode,default
bindsc=SHIFT,d,setlayout,vertical_deck
bindsc=SHIFT,d,setkeymode,default

## fair
bindsc=NONE,f,setlayout,fair
bindsc=NONE,f,setkeymode,default
bindsc=SHIFT,f,setlayout,vertical_fair
bindsc=SHIFT,f,setkeymode,default

binds=NONE,Escape,setkeymode,default
