## shadow
# shadowscolor=0x000000ff

## base colors
rootcolor=0x1a1b26ff
bordercolor=0x16161eff
focuscolor=0x7aa2f7ff
splitcolor=0x9ece6aff
urgentcolor=0xf7768eff
dropcolor=0x7aa2f7aa
maximizescreencolor=0x9ece6aff
scratchpadcolor=0x7dcfffff
globalcolor=0xbb9af7ff
overlaycolor=0xff9e64ff

## group bars
group_bar_decorate_fg_color=0xc0caf5ff
group_bar_decorate_bg_color=0x16161eff
group_bar_decorate_focus_fg_color=0x7aa2f7ff
group_bar_decorate_focus_bg_color=0x16161eff
# group_bar_decorate_border_color=0x7aa2f7ff

## jump labels
jump_label_decorate_fg_color=0xc0caf5ff
jump_label_decorate_bg_color=0x16161eff
jump_label_decorate_focus_fg_color=0x7aa2f7ff
jump_label_decorate_focus_bg_color=0x16161eff
# jump_label_decorate_border_color=0xbb9af7ff
