## monitor backlight
monitorrule=model:0x4171,scale:2,hdr:1,hdr_min_lum:0.005,hdr_max_lum:616.884,hdr_max_avg_lum:400.0
bind=NONE,XF86MonBrightnessUp,spawn,brightnessctl -d intel_backlight s +5%
bind=NONE,XF86MonBrightnessDown,spawn,brightnessctl -d intel_backlight s 5%- -n 5%
