## clamshell mode if reloading the config
exec=mon clamshell

## disable/enable laptop monitor on lid close/open
switchbind=fold,spawn_shell,mmsg dispatch disable_monitor,eDP-1
switchbind=unfold,spawn_shell,mmsg dispatch enable_monitor,eDP-1
