## xwayland
xwayland_ignore_scale=0 
xwayland_persistence=0

## graphics
# syncobj_enable=1
# allow_tearing=0

## lockscreen
# allow_lock_transparent=0

## shortcut inhibit
# allow_shortcuts_inhibit=1

## focus
# focus_on_activate=1
# sloppyfocus=1
# warpcursor=1
# focus_cross_monitor=0
# focusdir_only_zone_overlap=1
# exchange_cross_monitor=0
# focus_cross_tag=0
# view_current_to_back=0

## tags
# tag_num=9
# tag_gather=0
# tag_carousel=0

## scratchpad
# scratchpad_cross_monitor=0
# single_scratchpad=1

## cursor 
cursor_hide_timeout=5
cursor_hide_on_keypress=1

## idle inhibit
# idleinhibit_ignore_visible=0
# idleinhibit_when_fullscreen=0

## overview
# hotarea_size=10
# enable_hotarea=0
# hotarea_disable_on_fullscreen=1
# hotarea_corner=2
# overcircle_center_ratio=0.5
# jump_labels=HJKLASDFGQWERTYUIOPZXCVBNM
