## blur
# blur=0
# blur_layer=0
# blur_optimized=1
# blur_params_radius=5
# blur_params_num_passes=1
# blur_params_noise=0.02
# blur_params_brightness=0.9
# blur_params_contrast=0.9
# blur_params_saturation=1.2

## opacity
# focused_opacity=1.0
# unfocused_opacity=1.0

## shadows
# shadows=0
# shadow_only_floating=1
# layer_shadows=0
# shadows_size=10
# shadows_blur=15
# shadows_position_x=0
# shadows_position_y=0

## borders
borderpx=2
# border_radius=0 // wlr-only don't exist
# border_radius_location_default=0
# no_border_when_single=0
# no_radius_when_single=0

## gaps
gappih=0
gappiv=0
gappoh=0
gappov=0
# overviewgappi=5
# overviewgappo=30
# smartgaps=0

## jump labels
jump_label_decorate_border_width=0
jump_label_decorate_corner_radius=0
jump_label_decorate_font_desc=monospace 12 Bold
# jump_label_decorate_padding_x=10
# jump_label_decorate_padding_y=10

## group bars
group_bar_height=24
group_bar_decorate_border_width=0
group_bar_decorate_corner_radius=0
group_bar_decorate_font_desc=monospace 12 Bold
# group_bar_decorate_padding_x=0
# group_bar_decorate_padding_y=0

## cursor
cursor_theme=capitaine-cursors-light
# cursor_size=24

# animations
animations=0
layer_animations=0
# animation_type_open=zoom
# animation_type_close=slide
# layer_animation_type_open=slide
# layer_animation_type_close=slide
# animation_fade_in=1
# animation_fade_out=1
# fadein_begin_opacity=0.5
# fadeout_begin_opacity=0.5
# zoom_initial_ratio=0.4
# zoom_end_ratio=0.8
# animation_duration_move=500
# animation_duration_open=400
# animation_duration_tag=300
# animation_duration_close=300
# animation_duration_focus=0
# animation_curve_open=0.46,1.0,0.29,0.99
# animation_curve_move=0.46,1.0,0.29,0.99
# animation_curve_tag=0.46,1.0,0.29,0.99
# animation_curve_close=0.46,1.0,0.29,0.99
# animation_curve_focus=0.46,1.0,0.29,0.99
# animation_curve_opafadein=0.46,1.0,0.29,0.99
# animation_curve_opafadeout=0.5,0.5,0.5,0.5
# tag_animation_direction=1

## special worspace
special_gappih=0
special_gappiv=0
special_gappoh=0
special_gappov=0
# special_dim=0.5

## scratchpad
# scratchpad_width_ratio=0.8
# scratchpad_height_ratio=0.9
